services:
  web:
    container_name: jaguar-web
    build: .
    command: python AdminPanel/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  bot:
    container_name: jaguar-bot
    build: .
    command: python Start.py
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

  db:
    container_name: jaguar-db
    image: postgres:16.3
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
