# Generated by Django 5.1.1 on 2024-10-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='clicks',
            field=models.SmallIntegerField(default=0, editable=False, verbose_name='Число кликов'),
        ),
        migrations.AddField(
            model_name='questions',
            name='operator_calls',
            field=models.SmallIntegerField(default=0, editable=False, verbose_name='Вызов оператора'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='category',
            field=models.CharField(choices=[('Медицинская справка', 'Медицинская справка'), ('Вождение', 'Вождение'), ('Теория', 'Теория'), ('Внутренние экзамены', 'Внутренние экзамены'), ('Экзамен в ГИБДД', 'Экзамен в ГИБДД'), ('Оплата услуг', 'Оплата услуг')], max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='city',
            field=models.CharField(choices=[('Воронеж', 'Воронеж'), ('Москва', 'Москва'), ('Санкт-Петербург', 'Санкт-Петербург')], max_length=20, verbose_name='Город'),
        ),
    ]
