# Generated by Django 5.1.1 on 2024-10-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_questions_clicks_questions_operator_calls_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.SmallIntegerField(verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Причина',
                'verbose_name_plural': 'Причины',
                'db_table': 'reasons',
            },
        ),
    ]
