# Generated by Django 5.1.1 on 2024-10-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasons',
            name='reason',
            field=models.TextField(verbose_name='Причина'),
        ),
    ]
