# Generated by Django 5.1.1 on 2024-10-21 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0004_alter_reasons_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='operator_calls',
        ),
        migrations.CreateModel(
            name='Clicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(verbose_name='Номер')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('operator_calls', models.SmallIntegerField(default=0, editable=False, verbose_name='Вызов оператора')),
                ('clicks', models.SmallIntegerField(default=0, editable=False, verbose_name='Число кликов')),
                ('category', models.CharField(choices=[('Медицинская справка', 'Медицинская справка'), ('Вождение', 'Вождение'), ('Теория', 'Теория'), ('Внутренние экзамены', 'Внутренние экзамены'), ('Экзамен в ГИБДД', 'Экзамен в ГИБДД'), ('Оплата услуг', 'Оплата услуг')], max_length=20, verbose_name='Категория')),
                ('city', models.CharField(choices=[('Воронеж', 'Воронеж'), ('Москва', 'Москва'), ('Санкт-Петербург', 'Санкт-Петербург')], max_length=20, verbose_name='Город')),
                ('click_time', models.DateTimeField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.questions', verbose_name='ID Вопроса')),
            ],
            options={
                'verbose_name': 'Клик',
                'verbose_name_plural': 'Клики',
                'db_table': 'clicks',
                'unique_together': {('city', 'category', 'question')},
            },
        ),
    ]
