# Generated by Django 5.1.1 on 2024-10-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0005_remove_questions_clicks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clicks',
            options={'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
    ]
