# Generated by Django 5.1.1 on 2024-10-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0006_alter_clicks_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clicks',
            table='statistics',
        ),
    ]
