# Generated by Django 5.1.1 on 2024-10-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_reasons_alter_questions_category_and_more'),
        ('Questions', '0008_statistics_delete_clicks'),
    ]

    operations = [
    ]
